### PR TITLE
version update

### PR DESCRIPTION
**Pull request by cmedlandho**

### CODE REVIEW

**Comment by zuzak** [comment]
This isn't a bug fix, so I'm not sure patch is [appropriate](https://semver.org/)?

**Comment by jjrobothamho** [comment]
@zuzak  Should it be coupled with https://github.com/UKHomeOffice/ms-uk-local-authorities/pull/3

**Comment by zuzak** [comment]
Probably, but it's fairly academic

**Comment by jjrobothamho** [comment]
Merging into MS-1036-Remove-unknown-from-local-authorities-drop-down  PR

**Pull request merged**
